Impleemnt changes from external fork
- Drop Python 3.9 support.
- Replace pylint+isort with ruff.
- Add markdownlintcli2 and blacken-docs dev tools.
- Move AppSettings to a separate module and update it.
- Create a logging module to instantiate logging.
- Add introspective endpoints under a new 'admin' group of routers.

Furthermore, update to use the non-dev version of OTEAPI Core.

diff --git a/.github/workflows/ci_tests.yml b/.github/workflows/ci_tests.yml
--- a/.github/workflows/ci_tests.yml
+++ b/.github/workflows/ci_tests.yml
@@ -8,55 +8,42 @@ on:
       - 'push-action/**'  # Allow pushing to protected branches (using CasperWA/push-protected)
 
 jobs:
-  pylint-safety:
+  pre-commit_safety:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
-      with:
-        fetch-depth: 2
+    - name: Checkout ${{ github.repository }}
+      uses: actions/checkout@v4
 
-    - name: Set up Python 3.9
+    - name: Set up Python 3.10
       uses: actions/setup-python@v5
       with:
-        python-version: '3.9'
+        python-version: '3.10'
 
     - name: Install dependencies
       run: |
         python -m pip install -U pip
         pip install -U setuptools wheel
-        pip install -U -r requirements.txt -r .dev/requirements_dev.txt -r .dev/requirements_ci.txt
+        pip install -U -r .dev/requirements_ci.txt
 
-    - name: Run pylint
-      run: pylint --rcfile=pyproject.toml --ignore-paths=tests/ --extension-pkg-whitelist='pydantic' --recursive=yes *.py app
-
-    - name: Run pylint - tests
-      run: pylint --rcfile=pyproject.toml --extension-pkg-whitelist='pydantic' --disable=C0415,W0621 tests
+    - name: Run pre-commit
+      continue-on-error: true
+      id: pre_commit
+      run: pre-commit run --all-files
 
     # ID: 70612
     #   Package: Jinja2
     #   Has been disputed by the maintainer and multiple third parties.
     #   For more information see: https://github.com/advisories/GHSA-f6pv-j8mr-w6rr
     - name: Run safety
-      run: pip freeze | safety check --stdin --ignore=70612
+      run: safety check -r requirements.txt -r .dev/requirements_ci.txt -r .dev/requirements_dev.txt -r .dev/requirements_release.txt --ignore=70612
 
-  docker:
-    runs-on: ubuntu-latest
-
-    strategy:
-      fail-fast: false
-      matrix:
-        docker-target: ["development", "production"]
-
-    steps:
-    - uses: actions/checkout@v4
-
-    - name: Build Dockerfile
+    - name: Fail if pre-commit failed
       run: |
-        docker build \
-          -f Dockerfile \
-          --target ${{ matrix.docker-target }} \
-          .
+        if [ ${{ steps.pre_commit.outcome }} == 'failure' ]; then
+          echo "Pre-commit failed (see above)"
+          exit 1
+        fi
 
   pytest:
     name: "pytest (Python ${{ matrix.python-version}} - Live Redis: ${{ matrix.live-redis }})"
@@ -65,7 +52,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        python-version: ["3.9", "3.10"]
+        python-version: ["3.10", "3.11", "3.12", "3.13"]
         live-redis: [true, false]
 
     services:
@@ -75,7 +62,8 @@ jobs:
           - 6379:6379
 
     steps:
-    - uses: actions/checkout@v4
+    - name: Checkout ${{ github.repository }}
+      uses: actions/checkout@v4
 
     - name: Set up Python ${{ matrix.python-version}}
       uses: actions/setup-python@v5
@@ -100,19 +88,19 @@ jobs:
             REDIS_HOST=redis
         fi
 
-        OTEAPI_REDIS_HOST=${REDIS_HOST} pytest -vvv --cov-report=xml --cov=app ${LIVE_REDIS}
+        OTEAPI_REDIS_HOST=${REDIS_HOST} pytest -vv --cov-report=xml --cov=app ${LIVE_REDIS}
       env:
         OTEAPI_REDIS_TYPE: redis
         OTEAPI_REDIS_PORT: 6379
 
     - name: Upload coverage to Codecov
-      if: matrix.python-version == '3.9' && github.repository == 'EMMC-ASBL/oteapi-services'
+      if: github.repository == 'EMMC-ASBL/oteapi-services'
       uses: codecov/codecov-action@v5
       with:
         token: ${{ secrets.CODECOV_TOKEN }}
-        name: oteapi-services
-        files: ./coverage.xml
-        flags: pytest
+        env_vars: PYTHON
+      env:
+        PYTHON: ${{ matrix.python-version }}
 
   docker-compose:
     runs-on: ubuntu-latest
